name: PR Closed Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: |
      github.event.pull_request.head.ref != 'main' &&
      github.event.pull_request.head.ref != 'stage'
    uses: FranklinZuniorr/CI-S3-TEST/.github/workflows/s3_build_upload_release.yml@main
    with:
      has_semantic_release: false
      run_tests: false
      run_lint: false
      run_tsc: false
      project_build_envs: none
      environment_type: clear_preview
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: none
      WF_GITHUB_TOKEN: none
