name: Deploy build production in S3

on:
  push:
    branches:
      - main
  workflow_call: {}

jobs:
  deploy_build_production_in_s3:
    uses: FranklinZuniorr/CI-S3-TEST/.github/workflows/ci_s3_deploy_multi_environment.yml@main
    with:
      project_build_envs: ${{ vars.PROJECT_BUILD_ENVS }}
      environment_type: prod
      has_semantic_release: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      WF_GITHUB_TOKEN: ${{ secrets.WF_GITHUB_TOKEN }}
